packages:
  - "../cr-sqlite/core"
  - "tsbuild-all"
  - "packages/browser-tests"
  - "packages/client-core"
  - "packages/client-server-common"
  - "packages/client-websocket"
  - "packages/crsqlite-wasm"
  - "packages/node-allinone"
  - "packages/node-tests"
  - "packages/p2p"
  - "packages/react"
  - "packages/rx-tbl"
  - "packages/sandbox"
  - "packages/server-core"
  - "packages/server-websocket"
  - "packages/xplat-api"
  - "packages/xplat-tests"
  - "deps/wa-sqlite"
